# Generated by Django 3.2.11 on 2022-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('structure_value', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('REMOVED', 'Removed'), ('ENABLED', 'Enabled')], max_length=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['structure_value', 'status'], name='campaigns_c_structu_384d4e_idx'),
        ),
    ]
