# Generated by Django 3.2.11 on 2022-02-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('REMOVED', 'Removed'), ('ENABLED', 'Enabled')], max_length=10)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='adgroup',
            index=models.Index(fields=['alias', 'status'], name='ad_groups_a_alias_0e834b_idx'),
        ),
    ]
